version: 1
formatters:
  default:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/naukri_auto_apply.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    formatter: default
  console:
    class: logging.StreamHandler
    formatter: default
root:
  level: INFO
  handlers: [file, console]
