name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/naukri-auto-apply:latest
    - name: Deploy to AWS EC2
      run: |
        echo "Placeholder: Implement AWS EC2 deployment"
        # Example: ssh into EC2, pull image, run container
        # ssh -i ${{ secrets.EC2_KEY }} ec2-user@your-ec2-ip << 'EOF'
        # docker pull ${{ secrets.DOCKER_USERNAME }}/naukri-auto-apply:latest
        # docker run -d --env-file config/.env ${{ secrets.DOCKER_USERNAME }}/naukri-auto-apply:latest
        # EOF
